name: CI Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Test
        run: echo "CI/CD working successfully"
